### ISSUE TITLE
Installation instructions for Windows

### ISSUE THREAD

**Issue by lfmcmillan** [dedalozzo/pygmentize#5]
The installation instructions for pygmentize are written for Linux users but there is no information about how to install Composer or pygmentize on Windows, for example. This is a problem because pygmentize is required for the minted package in LaTeX, which is otherwise easily available on Windows except for its dependency on pygmentize.

**Comment by dedalozzo** [comment]
Hello, you do not need to install Pygmentize or Composer. Let me explain.

The Minted LaTeX package does not use Pygmentize the Composer package but it uses Pygments. Pygmentize (the package I wrote) is a PHP wrapper of the pygmentize command line utility, which is included in the Pygments package. Pygments is a Python library, which includes the pygmentize command line utility.

The Composer package I wrote and the above mentioned utility have the same name, but one is the command line tool, the other one is a wrapper over this command line tool, so that Pygments can be used not only from Python but from PHP as well.

To use Minted you need to install Pygments (the Python library) only. To install Pygments you need to run the command:

```
pip install Pygments
```

Please read the section Prerequisites of the [minted package documentation](https://anorien.csc.warwick.ac.uk/mirrors/CTAN/macros/latex/contrib/minted/minted.pdf).

**Comment by lfmcmillan** [comment]
But the instructions still suggest you need Composer to install Pygmentize, and don't bother to consider that you can't run pip on Windows without doing a lot of pre-setup like installing a pip installer. The instructions are still written from a Linux point of view without any indication that there might be more steps involved for Windows users.
